### ISSUE TITLE
question_1

### ISSUE THREAD

**Issue by xuyonglai** [evastgh/Minimal_Current#1]
Hello, i use Borromean rings boundary as the input with the same operations like your viedo.
However,  the result is missing a lot of faces.  I also found Squared Enneper surface boundary also missing faces.
Why？Is there something wrong with my operations?
Thank you!!!
![Snipaste_2021-11-04_21-47-39](https://user-images.githubusercontent.com/71511255/140328662-7cb22ecd-003e-465f-b755-1fd1bc434f52.png)
![Snipaste_2021-11-04_22-01-48](https://user-images.githubusercontent.com/71511255/140328811-a8117f85-3ce3-4492-bd89-53cb76238186.png)
![Snipaste_2021-11-04_21-47-11](https://user-images.githubusercontent.com/71511255/140328943-685ae570-fd73-41cf-a7f5-5e0c75f11916.png)
![Snipaste_2021-11-04_22-01-33](https://user-images.githubusercontent.com/71511255/140328978-b0c7b581-2004-4e42-b04f-fcaa800f2e39.png)

**Comment by evastgh** [comment]
Not a problem! Give it a few more iterations or change the cut off for Alpha value to something smaller. The algorithm is fast to resolve the surface embedding (surface's positioning in the space) but the confidence level (surface opacity) will take more time.

**Comment by xuyonglai** [comment]
I get it, thank you very much！！！！！

**Comment by xuyonglai** [comment]
But there are still some problems for some examples, the results don’t seem to be the minimal surface. For example,  a boundary defined on the cube:   
![image](https://user-images.githubusercontent.com/71511255/143157399-5ffe5516-af68-4558-b718-f5fa8ed80b0c.png)
Its boundary coordinates are：
v 0 2 2
v 1 2 -1
v -2 2 0
v -2 -1 1
v -2 0 -2
v 1 1 -2
v 0 -2 -2
v -1 -2 1
v 2 -2 0
v 2 1 -1
v 2 0 2
v -1 -1 2
The result is: 
![image](https://user-images.githubusercontent.com/71511255/143157923-2f75c2a2-286f-4422-b4e3-8cd23df8ce93.png)
Also, another boundary curve with coordinates ：
v 0 1 -1
v -0.1 1 -0.1
v -1 1 0
v -1 0.1 0.1
v -1 0 1
v -0.1 0.1 1
v 0 1 1
v 0.1 1 0.1
v 1 1 0
v 1 0.1 0.1
v 1 0 1
v 0.1 -0.1 1
v 0 -1 1
v 0.1 -1 0.1
v 1 -1 0 
v 1 -0.1 -0.1
v 1 0 -1
v 0.1 -0.1 -1
v 0 -1 -1
v -0.1 -1 -0.1
v -1 -1 0
v -1 -0.1 -0.1
v -1 0 -1
v -0.1 0.1 -1
![image](https://user-images.githubusercontent.com/71511255/143158592-65b2805a-f006-4a25-b557-95c23dfe1b30.png)
The result is also very strange.  When tested these two examples,  i used more iterations and lower Alpha value.  Can you try these two examples？ I think the correct result should be like：
![image](https://user-images.githubusercontent.com/71511255/143159011-2eb84073-e358-4b15-9e69-9c65004dab78.png)

**Comment by evastgh** [comment]
The issue described in the above comment is superpositioning minimal surfaces due to symmetric boundary curve. It has been resolved by perturbing the metric (essentially penalizing the minimal surface from passing through a certain region in space).
